### ISSUE TITLE
-lpthread or -pthread (and suppressing warnings)

### ISSUE THREAD

**Issue by fat-tire** [dirtycow/dirtycow.github.io#11]
Minor thing, but  [dirtyc0w.c](https://raw.githubusercontent.com/dirtycow/dirtycow.github.io/master/dirtyc0w.c) says to build with:

     gcc -lpthread dirtyc0w.c -o dirtyc0w

This (at least for me, gcc 6.2.0) results in errors:

     undefined reference to `pthread_create'
     undefined reference to `pthread_join

Using:

     gcc -pthread dirtyc0w.c -o dirtyc0w

Works fine.  Also some warnings can be gotten rid of by adding

     #include <sys/stat.h>
     #include <unistd.h>

I got rid of the rest by adding:

     #include <stdint.h>

Then changing:

     lseek(f,map,SEEK_SET);

to

    lseek(f, (uintptr_t) map,SEEK_SET);

and

     printf("mmap %x\n\n",map);

to

     printf("mmap %x\n\n",(uintptr_t) map);

Dunno if this is correct- it very well may not be- but it builds quietly for me now on my raspberry pi.  So there ya go.

**Comment by multiwebinc** [comment]
After applying the above changes I was also getting:

```
dirtyc0w.c: In function ‘main’:
dirtyc0w.c:99:3: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
   printf("mmap %x\n\n",(uintptr_t) map);
   ^
```

So I changed line 99 to:

    printf("mmap %lu\n\n",(uintptr_t) map);

Now I have no output at all. Maybe because it's patched?

**Comment by tempuser1909** [comment]
@multiwebinc Try changing 
Line 99: printf("mmap %x\n\n",(uintptr_t) map);
to
Line 99  : unsigned int map_t = (uintptr_t) map;
Line 100: printf("mmap %x\n\n", map_t);

Making this change works for me.

**Comment by sbrl** [comment]
Erm why was this closed, @dirtycow?

**Comment by therealbstern** [comment]
The libc printf format character for a void pointer is `%p`, no casts needed.

**Comment by dirtycow** [comment]
https://github.com/dirtycow/dirtycow.github.io/pull/17

**Comment by dirtycow** [comment]
Didn't #17 fixed all of this?
