### ISSUE TITLE
Your store is a little expensive

### ISSUE THREAD

**Issue by yeltsin** [dirtycow/dirtycow.github.io#19]
:rabbit:

**Comment by dirtycow** [comment]
they are designer clothes

**Comment by lewisje** [comment]
they see me trollin'...

**Comment by unixfox** [comment]
Has anyone already bought something on your market @dirtycow ?

**Comment by dirtycow** [comment]
I hope not, I forgot the password to the store.

**Comment by lewisje** [comment]
Use the very vuln your site mentions, to break in and reset your password. ;-D
