### ISSUE TITLE
Compiled list of patches

### ISSUE THREAD

**Issue by Electronickss** [dirtycow/dirtycow.github.io#28]
Would it be possible to get either in the wiki or gist attached to this page, a list of distro's and the patched kernel version?

**Comment by dirtycow** [comment]
Sure! Either would be fine. Are you interested to collect these?

**Comment by Electronickss** [comment]
Is there a good way to verify that info? I can add some of what I found but I'm not 100% on how correct it is

**Comment by dirtycow** [comment]
Wikipedia style, do your best and if there are omissions or errors, just depend on others to help out.

**Comment by unixfox** [comment]
I can give some help into this work if you want to.

**Comment by Electronickss** [comment]
From what I found:

```
*4.8.0-26.28 for Ubuntu 16.10
*4.4.0-45.66 for Ubuntu 16.04 LTS
*3.13.0-100.147 for Ubuntu 14.04 LTS
*3.2.0-113.155 for Ubuntu 12.04 LTS
*3.16.36-1+deb8u2 for Debian 8
*3.2.82-1 for Debian 7
*4.7.8-1 for Debian unstable
```

^patched versions

If anyone wants to start a pull on the wiki. @unixfox ?

**Comment by Electronickss** [comment]
@unixfox

**Comment by unixfox** [comment]
@Electronickss Sure, maybe create a dedicated page for that ?

**Comment by unixfox** [comment]
```
*4.4.26-1 for ArchLinux (linux-lts package)
*4.8.3 for ArchLinux (linux package)
```

**Comment by Electronickss** [comment]
Yeah that's what I was thinking. There's also a spot in the vulnerability details page where it mentions the date it was patched. We could link to the list of patches page. It would probably be nice for less experienced users to include:

> Check your version with `uname -ar`

Or something like that

**Comment by kcgthb** [comment]
_shameless plug_

In case it could help, there are instructions for patching RHEL/CentOS 6.x here:
https://github.com/kcgthb/RHEL6.x-COW

**Comment by Electronickss** [comment]
https://github.com/dirtycow/dirtycow.github.io/wiki/Patched-Kernel-Versions

**Comment by dirtycow** [comment]
Excellent. Thank you @Electronickss

**Comment by dirtycow** [comment]
And everyone else that contributed of course 👍 :-)
